name: NIPS 2015 Workshop on Black Box Learning and Inference
markdown: redcarpet
pygments: true

navigation:
- text: Description
  url: /
- text: Submissions
  url: /submissions/
- text: Schedule
  url: /schedule/
- text: Organizers 
  url: /organizers/
