name: NIPS 2015 Workshop on Black Box Learning and Inference
markdown: redcarpet
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]

navigation:
- text: Description
  url: /
- text: Submissions
  url: /submissions/
- text: Abstracts
  url: /accepted-papers/
- text: Schedule
  url: /schedule/
- text: Organizers 
  url: /organizers/
